# Dutch translations for spynl.main.
# Copyright (C) 2016 Softwear BV
# This file is distributed under the same license as the spynl.main project.
# FIRST AUTHOR <EMAIL@ADDRESS>, 2016.
#
msgid ""
msgstr ""
"Project-Id-Version: spynl.main 5.48.rc1\n"
"Report-Msgid-Bugs-To: EMAIL@ADDRESS\n"
"POT-Creation-Date: 2018-07-16 13:48+0200\n"
"PO-Revision-Date: 2016-09-28 16:22+0200\n"
"Last-Translator: Nicolas <nicolas@softwear.nl>\n"
"Language: nl\n"
"Language-Team: nl <LL@li.org>\n"
"Plural-Forms: nplurals=2; plural=(n != 1)\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=utf-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Generated-By: Babel 2.5.1\n"

#. This is a Spynl web application. You can get more information at
#. about/endpoints, about/ini, about/versions, about/build and
#. about/environment.
#: spynl/main/about/endpoints.py:54
msgid "about-message"
msgstr ""

#. Sorry, there was a problem with your request. If the problem persists,
#. please contact support team. Our apologies for the inconvenience.
#: spynl/main/error_views.py:22
msgid "validation-error"
msgstr "Er was een probleem met uw verzoek. Neem contact op met de servicedesk als dit blijft gebeuren. Onze excuses voor het ongemak."

#. No endpoint found for path '${path}'.
#: spynl/main/error_views.py:66
msgid "no-endpoint-for-path"
msgstr "Geen endpoint gevonden voor pad '${path}'."

#. Permission to '${permission}' ${context} was denied.
#: spynl/main/error_views.py:72
msgid "permission-denial"
msgstr "'${permission}' toegang is geweigerd voor ${context}."

#. An internal server error occured.
#: spynl/main/error_views.py:81 spynl/main/error_views.py:116
msgid "internal-server-error"
msgstr "Interne serverfout."

#: spynl/main/exceptions.py:149
msgid "bad-origin"
msgstr "Requests naar Spynl zijn niet toegestaan vanaf origin '${origin}'."

#. Missing required parameter: ${param}
#: spynl/main/exceptions.py:166
msgid "missing-parameter"
msgstr "Er ontbreekt een verplichte parameter: ${param}."

#. Illegal parameter: ${param}
#: spynl/main/exceptions.py:177
msgid "illegal-parameter"
msgstr "Ongeldige parameter: ${param}."

#: spynl/main/exceptions.py:190
msgid "bad-validation-instructions"
msgstr "De beschrijving voor dit endpoint kan niet gebruikt worden: ${error}."

#: spynl/main/exceptions.py:204
msgid "invalid-response"
msgstr "Spynl kon helaas geen valide response genereren: ${error}"

#: spynl/main/exceptions.py:217
msgid "email-tmpl-not-found"
msgstr "De e-mailtemplate <${template}> kan niet worden gevonden."

#: spynl/main/exceptions.py:229
msgid "email-recipient-not-given"
msgstr ""

#: spynl/main/serial/exceptions.py:14
msgid "undetermined-content-type-exception"
msgstr "De request heeft een body maar de content type is niet herkent."

#. Unsupported content type: "${type}"
#: spynl/main/serial/exceptions.py:24
msgid "unsupported-content-type-exception"
msgstr "Content type is niet ondersteund: \"${type}\""

#: spynl/main/serial/exceptions.py:36
msgid "deserialization-unsupported-exception"
msgstr "Deserialisation van content type \"${type}\" is niet ondersteund."

#: spynl/main/serial/exceptions.py:48
msgid "serialization-unsupported-exception"
msgstr "Serialisation van content type \"${type}\" is niet ondersteund."

#: spynl/main/serial/exceptions.py:61
msgid "malformed-request-exception-type"
msgstr "Misvormd \"${type}\" request: ${request}"

#. Malformed request: ${type}
#: spynl/main/serial/exceptions.py:66
msgid "malformed-request-exception"
msgstr "Misvormd request: ${request}"

#. The value '${value}' for key '${key}' does not seem to be a valid date
#. string that conforms to ${format}.
#: spynl/main/serial/objects.py:118
msgid "date-decode-value-error"
msgstr "De waarde '${value}' voor key '${key}' lijkt geen geldige datastring te zijn wat past binnen ${format}."

#. Unexpected end of input.
#: spynl/main/urlson.py:116
msgid "unexpected-end-of-input"
msgstr "Onverwacht einde van input."

#. "${value}" could not be parsed as ${class}
#: spynl/main/utils.py:325
msgid "parse-value-exception-as-class"
msgstr "\"${value}\" kon niet worden ontleed naar ${class}."

#. ${class} is not a class. Cannot parse value "${value}".
#: spynl/main/utils.py:333
msgid "parse-value-exception-not-class"
msgstr "${class} is geen class. Kan waarde \"${value}\" niet ontleden."

#. "${value}" could not be parsed into any class in ${classes}
#: spynl/main/utils.py:342
msgid "parse-value-exception-any-class"
msgstr "\"${value}\" kon niet worden ontleed in een class in ${classes}."

#. No message available.
#: spynl/main/utils.py:485
msgid "no-message-available"
msgstr "Geen bericht beschikbaar."

#. Validations should be a list.
#: spynl/main/validation.py:69
msgid "validations-is-not-list"
msgstr "validations moet een lijst zijn."

#. Missing field: ${field}
#: spynl/main/validation.py:76
msgid "bad-validation-instructions-missing-field"
msgstr "Ontbrekend veld: ${field}."

#. Setting "in" should be either "request" or "response"
#: spynl/main/validation.py:81
msgid "bad-validation-instructions-setting-in"
msgstr "Setting \"in\" zou of \"request\" of \"response\" moeten zijn."

#. The schema ${schema} is not valid
#: spynl/main/validation.py:128
msgid "bad-validation-instructions-bad-schema"
msgstr "De beschrijving voor de validatie voor deze endpoint kan niet worden gebruikt: ${error}"

#. The required schema ${schema} could not be found to perform validation.
#: spynl/main/validation.py:134
msgid "bad-validation-instructions-schema-not-found"
msgstr "Kon schema ${schema} niet vinden om te valideren."

#~ msgid "pong"
#~ msgstr "peng"

#~ msgid "mail-template-file-string"
#~ msgstr "Specificeer een templatebestand of \"body_string\""

#~ msgid "invalid-query-string-or-post-body-parameters"
#~ msgstr ""

